name: GitHub Pages cron deploy

on:
  schedule:
    # 分 時 日 月 曜日 コマンド  UTC時間
    # 毎日日本時間3時に実行(設定時間の9時間後が日本時間になる)
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  update_articles:
    runs-on: ubuntu-latest 
    # Python3がプリインストールされており、バージョンも特に気にしないため、actions/setup-pythonは今回は使わない
    name: Update constants/articles.ts and marge
    steps:
      # デフォルトブランチをチェックアウトする
      - uses: actions/checkout@v3
      # pythonモジュールをGithub Actionsコンテナ内に復元する
      - name: Setup python modules
        run: pip3 install -r requirements.txt
      # QiitaApiから記事を取得し、コードを自動生成するスクリプトを実行
      - name: Generate articles.ts
        run: python3 -B scripts/articles_generator.py constants/articles.ts
      # コミットしてプッシュ
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update constants/articles.ts'
  deploy:
    # 上のjobが終わってから実行（設定しない場合並列に実行される）
    needs: update_articles

    runs-on: ubuntu-latest
    name: Checkout, build, deploy
    steps:
      # jobごとにコンテナが異なるのでチェックアウトし直す
      - uses: actions/checkout@v3
      # yarn (またはyarn install)でパッケージを取得
      - name: Restore packages
        run: yarn
      # ビルド（中身は環境変数の指定とnuxt build）
      - name: Build
        run: yarn generate:main
      # Dploy Github Pages from the main branch to the root directory
      - name: Deploy (puth dist dir to gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: main