name: github-pages-update

on:
  # push:
    # branches: ["main"]

  workflow_dispatch:

  schedule:
    # 分 時 日 月 曜日 コマンド  UTC時間
    # 毎日日本時間3時に実行(設定時間の9時間後が日本時間になる)
    - cron: '0 15 28 * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update_publication_list:
    runs-on: ubuntu-latest
    steps:
      # Checkout my repository
      - uses: actions/checkout@v4
        with:
          use-public-rspm: true

      # Setup pandoc to render rmarkdown
      - uses: r-lib/actions/setup-pandoc@v2

      # Setup R
      - uses: r-lib/actions/setup-r@v2

      # # Install R packages
      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: |
      #       any::htmltools
      #       any::rentrez
      #       any::reticulate
      #       any::jsonlite
      #
      # # Execute the web_deploy.R script.
      # - name: Render Rmarkdown files and Commit Results
      #   run: Rscript R/web_deploy.R

      # Commit changes
      - name: Commit files
        run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add -u
        git add publist_archive/*
        git commit -m 'Render rmarkdown files' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
